application:
  image: waldemarnt/cakephp
  volumes:
      - .:/var/www/cake-app
  tty: true
mysql:
  image: mysql
  ports:
      - 3386:3306    
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: siep
    MYSQL_USER: root
    MYSQL_PASSWORD: root    
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  restart: always
  links:
      - mysql
  ports:
      - 8183:80
  environment:
    PMA_HOST: mysql
    PMA_PORT: 3306
    PMA_PASSWORD: root
    PMA_ARBITRARY: 1
php:
  image: bitnami/php-fpm
  expose:
      - 9000
  volumes_from:
      - application
  links:
      - mysql    
nginx:
  image: waldemarnt/cakephp-nginx
  ports:
      - 80:80
  links:
      - php
  volumes_from:
      - application
  volumes:
      - ./logs/nginx/:/var/log/nginx    